<?php

namespace apivp1\models;

use yii\base\InvalidConfigException;
use yii\db\ActiveQuery;

/**
 * Class User
 * @package apivp1\models
 */
class User extends \common\models\User
{
	public const SCENARIO_UPDATE_SELF_ACCOUNT='USER_UPDATE';
    /**
     * @return ActiveQuery
     */
    public function getProgramGroupViews(): ActiveQuery
    {
        return $this->hasMany(ProgramGroupView::class, ['user_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     * @throws InvalidConfigException
     */
    public function getProgramGroupsViewed(): ActiveQuery
    {
        return $this->hasMany(ProgramGroup::class, ['id' => 'program_group_id'])
            ->viaTable('program_group_view', ['user_id' => 'id']);
    }

    public function scenarios() {
	    $scenarios= parent::scenarios(); // TODO: Change the autogenerated stub
	    $scenarios[self::SCENARIO_UPDATE_SELF_ACCOUNT] = [
		     'id_card_number', 'name_zh','phone_number','is_verify'
	    ];
	    return $scenarios;
    }
}
