<?php
return [
    'client1' => [
        'id' => 1,
        'name_zh' => 'Client1',
        'name_pinyin' => 'diyikehu',
        'name_en' => 'First Client',
        'nickname' => 'first nickname',
        'is_male' => 1,
        'is_kid' => 1,
        'family_id' => 1,
        'created_by' => 1,
        'updated_by' => 2,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    'client2' => [
        'id' => 2,
        'name_zh' => 'Client2',
        'name_pinyin' => 'dierkehu',
        'name_en' => 'Second Client',
        'nickname' => 'second nickname',
        'is_male' => 0,
        'is_kid' => 1,
        'family_id' => 2,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramClientACest Modify program-client relation
    'client3' => [
        'id' => 3,
        'name_zh' => 'Client3',
        'name_pinyin' => 'disankehu',
        'name_en' => 'Third Client',
        'nickname' => 'third nickname',
        'is_male' => 0,
        'is_kid' => 1,
        'family_id' => 10,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used to test client-search DO NOT UPDATE/DELETE!
    'client4' => [
        'id' => 4,
        'name_zh' => 'Client4',
        'name_pinyin' => 'disikehu',
        'name_en' => 'Fourth Client',
        'nickname' => 'fourth nickname',
        'is_male' => 0,
        'is_kid' => 1,
        'family_role_id' => 1,
        'family_id' => 4,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used to test client-search DO NOT UPDATE/DELETE!
    'client5' => [
        'id' => 5,
        'name_zh' => 'Client5',
        'name_pinyin' => 'diwukehu',
        'name_en' => 'Fifth Client',
        'nickname' => 'fifth nickname',
        'is_male' => 1,
        'is_kid' => 1,
        'family_role_id' => 2,
        'phone_number' => '123 456 7890',
        'family_id' => 4,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used to test client-search DO NOT UPDATE/DELETE!
    'client6' => [
        'id' => 6,
        'name_zh' => 'Client6',
        'name_pinyin' => 'diliukehu',
        'name_en' => 'Sixth Client',
        'nickname' => 'sixth nickname',
        'is_male' => 0,
        'is_kid' => 0,
        'family_id' => 4,
        'family_role_id' => 3,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used to test client-search DO NOT UPDATE/DELETE!
    'client7' => [
        'id' => 7,
        'name_zh' => 'Client7',
        'name_pinyin' => 'diqikehu',
        'name_en' => 'Seveth Client',
        'nickname' => 'seventh nickname',
        'is_male' => true,
        'is_kid' => false,
        'family_id' => 4,
        'family_role_id' => 2,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used to test ClientHelper->getRole
    'client8' => [
        'id' => 8,
        'name_zh' => 'Client8',
        'name_pinyin' => 'ecl',
        'name_en' => '8 Client',
        'nickname' => '8 nickname',
        'is_male' => 1,
        'is_kid' => 0,
        'family_id' => 4,
        'family_role_id' => 5,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by FinancialCest, not modified
    'client9' => [
        'id' => 9,
        'name_zh' => 'Client9',
        'name_pinyin' => 'ncl',
        'name_en' => '9 Client',
        'nickname' => '9 nickname',
        'is_male' => 1,
        'is_kid' => 1,
        'family_id' => 9,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by FinancialCest, not modified
    'client10' => [
        'id' => 10,
        'name_zh' => 'Client10',
        'name_pinyin' => 'ncl',
        'name_en' => '10 Client',
        'nickname' => '10 nickname',
        'is_male' => 0,
        'is_kid' => 1,
        'family_id' => 9,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by LocationCest to count program clients
    'client11' => [
        'id' => 11,
        'name_zh' => 'Client11',
        'name_pinyin' => 'elcl',
        'name_en' => '11 Client',
        'nickname' => '11 nickname',
        'is_male' => 0,
        'is_kid' => 1,
        'family_id' => 9,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by LocationCest to count program clients
    'client12' => [
        'id' => 12,
        'name_zh' => 'Client12',
        'name_pinyin' => 'twcl',
        'name_en' => '12 Client',
        'nickname' => '12 nickname',
        'is_male' => 1,
        'is_kid' => 1,
        'family_id' => 9,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'client13' => [
        'id' => 13,
        'name_zh' => 'Client13',
        'name_pinyin' => 'thrcl',
        'name_en' => '13 Client',
        'nickname' => '13 nickname',
        'is_male' => 0,
        'is_kid' => 0,
        'family_id' => 11,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,

        // Added fields to test program/export
        'wechat_id' => 'momWechat',
        'passport_number' => 'G12345678',
        'passport_expire_date' => '2022-12-03',
        'phone_number' => '123 4567 8901',
        'email' => 'momEmail@qq.com',
        'id_card_number' => '1234567890',
    ],
    // Used by ProgramGroupCest
    'client14' => [
        'id' => 14,
        'name_zh' => 'Client14',
        'name_pinyin' => 'frtcl',
        'name_en' => '14 Client',
        'nickname' => '14 nickname',
        'is_male' => 1,
        'is_kid' => 0,
        'family_id' => 11,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,

        // Added fields to test program/export
        'wechat_id' => 'dadWechat',
        'passport_number' => 'F12345678',
        'passport_expire_date' => '2027-10-13',
        'phone_number' => '157 4567 8901',
        'email' => 'dadEmail@qq.com',
        'id_card_number' => '23456789012',
    ],
    // Used by ProgramGroupCest
    'client15' => [
        'id' => 15,
        'name_zh' => 'Client15',
        'name_pinyin' => 'fftcl',
        'name_en' => '15 Client',
        'nickname' => '15 nickname',
        'is_male' => 1,
        'is_kid' => 1,
        'family_id' => 11,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,

        // Added fields to test program/export
        'passport_number' => 'K12345678',
        'passport_expire_date' => '2027-10-13',
        'id_card_number' => '45678901234',
    ],
    // Used by ProgramGroupCest
    'client16' => [
        'id' => 16,
        'name_zh' => 'Client16',
        'name_pinyin' => 'sxtcl',
        'name_en' => '16 Client',
        'nickname' => '16 nickname',
        'is_male' => 0,
        'is_kid' => 1,
        'family_id' => 11,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,

        // Added fields to test program/export
        'passport_number' => 'J12345678',
        'passport_expire_date' => '2027-10-13',
        'id_card_number' => '67890123456',
    ],
    // Used by ProgramGroupCest
    'client17' => [
        'id' => 17,
        'name_zh' => 'Client17',
        'name_pinyin' => 'sthcl',
        'name_en' => '17 Client',
        'nickname' => '17 nickname',
        'is_male' => 0,
        'is_kid' => 0,
        'family_id' => 12,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'client18' => [
        'id' => 18,
        'name_zh' => 'Client18',
        'name_pinyin' => 'ethcl',
        'name_en' => '18 Client',
        'nickname' => '18 nickname',
        'is_male' => 0,
        'is_kid' => 1,
        'family_id' => 12,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'client19' => [
        'id' => 19,
        'name_zh' => 'Client19',
        'name_pinyin' => 'nthcl',
        'name_en' => '19 Client',
        'nickname' => '19 nickname',
        'is_male' => 0,
        'is_kid' => 0,
        'family_id' => 13,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'client20' => [
        'id' => 20,
        'name_zh' => 'Client20',
        'name_pinyin' => 'twtcl',
        'name_en' => '20 Client',
        'nickname' => '20 nickname',
        'is_male' => 1,
        'is_kid' => 1,
        'family_id' => 13,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'client21' => [
        'id' => 21,
        'name_zh' => 'Client21',
        'name_pinyin' => 'toncl',
        'name_en' => '21 Client',
        'nickname' => '21 nickname',
        'is_male' => 1,
        'is_kid' => 1,
        'family_id' => 13,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Deleted by ClientACest->delete()
    'client22' => [
        'id' => 22,
        'name_zh' => 'Client22',
        'name_pinyin' => 'ttwcl',
        'name_en' => '22 Client',
        'nickname' => '22 nickname',
        'is_male' => 0,
        'is_kid' => 0,
        'family_id' => 2,
        'family_role_other' => null,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
];
