<?php
return [
    'programFamily1' => [
        'program_id' => '1',
        'family_id' => '1',
        'remarks' => 'Family Remarks',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    'programFamily2' => [
        'program_id' => '1',
        'family_id' => '2',
        'remarks' => 'Family Remarks',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    'programFamily3' => [
        'program_id' => '3',
        'family_id' => '2',
        'remarks' => 'Family Remarks',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by FinancialCest, not modified
    'programFamily4' => [
        'program_id' => 5,
        'family_id' => 9,
        'cost' => 2000,
        'discount' => 500,
        'final_cost' => 1500,
        'remarks' => 'Used by FinancialCest to check program balance',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by FinancialCest, not modified
    'programFamily5' => [
        'program_id' => 1,
        'family_id' => 9,
        'cost' => 4000,
        'discount' => 0,
        'final_cost' => 4000,
        'remarks' => 'Used by FinancialCest to check program balance',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'programFamily6' => [
        'program_id' => 11,
        'family_id' => 11,
        'cost' => 120000,
        'discount' => 0,
        'final_cost' => 120000,
        'status' => 1,
        'remarks' => 'There is an urgent problem with their flights',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'programFamily7' => [
        'program_id' => 11,
        'family_id' => 12,
        'cost' => 40000,
        'discount' => 0,
        'final_cost' => 40000,
        'status' => 7,
        'remarks' => 'All good, ready to go!',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'programFamily8' => [
        'program_id' => 11,
        'family_id' => 13,
        'status' => 2,
        'remarks' => 'It seems like we won\'t be able to get their visas.',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramFamilyControllerTest->testSafeUnlinkWithValidData()
    'programFamily8' => [
        'program_id' => 1,
        'family_id' => 14,
        'status' => 1,
        'remarks' => 'Deleted by ProgramFamilyControllerTest->testSafeUnlinkWithValidData()',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by FinancialCest to check program balance
    'programFamily9' => [
        'program_id' => 15,
        'family_id' => 9,
        'cost' => 40000,
        'discount' => 0,
        'final_cost' => 40000,
        'status' => 1,
        'remarks' => 'Used by FinancialCest to check program balance',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by FinancialCest to check program balance
    'programFamily10' => [
        'program_id' => 16,
        'family_id' => 9,
        'cost' => 60000,
        'discount' => 5700,
        'final_cost' => 54300,
        'status' => 1,
        'remarks' => 'Used by FinancialCest to check program balance',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
];
