<?php
return [
    'programClient1' => [
        'program_id' => 1,
        'client_id' => 1,
        'remarks' => 'ProgramClient remarks',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    'programClient2' => [
        'program_id' => 1,
        'client_id' => 2,
        'remarks' => 'ProgramClient remarks',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    'programClient3' => [
        'program_id' => 3,
        'client_id' => 3,
        'remarks' => 'ProgramClient remarks',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by FinancialCest, not modified
    'programClient4' => [
        'program_id' => 5,
        'client_id' => 9,
        'remarks' => 'ProgramClient remarks',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by FinancialCest, not modified
    'programClient5' => [
        'program_id' => 5,
        'client_id' => 10,
        'remarks' => 'ProgramClient remarks',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by FinancialCest, not modified
    'programClient6' => [
        'program_id' => 1,
        'client_id' => 10,
        'remarks' => 'ProgramClient remarks',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by LocationCest, not modified
    'programClient7' => [
        'program_id' => 1,
        'client_id' => 11,
        'remarks' => 'ProgramClient remarks',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by LocationCest, not modified
    'programClient8' => [
        'program_id' => 1,
        'client_id' => 12,
        'remarks' => 'ProgramClient remarks',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'programClient9' => [
        'program_id' => 11,
        'client_id' => 13,
        'remarks' => 'Nobody has set the status for this client yet',
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'programClient10' => [
        'program_id' => 11,
        'client_id' => 14,
        'remarks' => 'This client\'s flight was ** cancelled **, need to buy a new one.',
        'status' => 1,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'programClient11' => [
        'program_id' => 11,
        'client_id' => 15,
        'remarks' => 'There is some type of problem here',
        'status' => 2,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'programClient12' => [
        'program_id' => 11,
        'client_id' => 16,
        'remarks' => 'The situation requires attention!',
        'status' => 3,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'programClient13' => [
        'program_id' => 11,
        'client_id' => 18,
        'remarks' => 'Waiting for something...',
        'status' => 4,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'programClient14' => [
        'program_id' => 11,
        'client_id' => 19,
        'remarks' => 'Processing',
        'status' => 5,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'programClient15' => [
        'program_id' => 11,
        'client_id' => 20,
        'remarks' => 'Almost done',
        'status' => 6,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Used by ProgramGroupCest
    'programClient16' => [
        'program_id' => 11,
        'client_id' => 21,
        'remarks' => 'All good!',
        'status' => 7,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Deleted by ClientACest->delete()
    'programClient17' => [
        'program_id' => 1,
        'client_id' => 22,
        'remarks' => 'Will be deleted',
        'status' => 7,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
    // Deleted by ClientACest->delete()
    'programClient18' => [
        'program_id' => 2,
        'client_id' => 22,
        'remarks' => 'Will be deleted',
        'status' => 7,
        'created_by' => 1,
        'updated_by' => 1,
        'created_at' => 1498028717,
        'updated_at' => 1498977098,
    ],
];
