<?php

/* @var $this yii\web\View */
?>

1. [Client](#man-client)
    1. [Viewing all clients](#man-client-index)
    2. [Viewing one client](#man-client-view)
    3. [Adding clients to the system](#man-client-create)
    4. [Updating a client](#man-client-update)
    5. [Deleting a client](#man-client-delete)
    6. [Client Internals](#man-client-internals)
        1. [Client dependencies](#man-client-dependencies)
        2. [Client dependents](#man-client-dependents)
        3. [Client EER diagram](#man-client-eer)
        4. [Client SQL](#man-client-sql)
1. [Family](#man-family)
    1. [Viewing all familys](#man-family-index)
    2. [Viewing one family](#man-family-view)
    3. [Adding familys to the system](#man-family-create)
    4. [Updating a family](#man-family-update)
    5. [Deleting a family](#man-family-delete)
    6. [Family Internals](#man-family-internals)
        1. [Family dependencies](#man-family-dependencies)
        2. [Family dependents](#man-family-dependents)
        3. [Family EER diagram](#man-family-eer)
        4. [Family SQL](#man-family-sql)
1. [Location](#man-location)
	1. [Viewing all locations](#man-location-index)
	2. [Viewing one location](#man-location-view)
	3. [Adding locations to the system](#man-location-create)
	4. [Updating a location](#man-location-update)
	5. [Deleting a location](#man-location-delete)
	6. [Location Internals](#man-location-internals)
		1. [Location dependencies](#man-location-dependencies)
		2. [Location dependents](#man-location-dependents)
		3. [Location EER diagram](#man-location-eer)
		4. [Location SQL](#man-location-sql)
2. [Program](#man-program)
	1. [Viewing all programs](#man-program-index)
	2. [Viewing one program](#man-program-view)
	3. [Adding programs to the system](#man-program-create)
	4. [Updating a program](#man-program-update)
	5. [Deleting a program](#man-program-delete)
	6. [Managing clients on a program](#man-program-manage-clients)
	7. [Managing families on a program](#man-program-manage-families)
	8. [Program Internals](#man-program-internals)
		1. [Program dependencies](#man-program-dependencies)
		2. [Program dependents](#man-program-dependents)
		3. [Program EER diagram](#man-program-eer)
		4. [Program SQL](#man-program-sql)
3. [Supplier](#man-supplier)
    1. [Viewing all suppliers](#man-supplier-index)
    2. [Viewing one supplier](#man-supplier-view)
    3. [Adding suppliers to the system](#man-supplier-create)
    4. [Updating a supplier](#man-supplier-update)
    5. [Deleting a supplier](#man-supplier-delete)
    6. [Managing clients on a supplier](#man-supplier-manage-clients)
    7. [Managing families on a supplier](#man-supplier-manage-families)
    8. [Supplier Internals](#man-supplier-internals)
        1. [Supplier dependencies](#man-supplier-dependencies)
        2. [Supplier dependents](#man-supplier-dependents)
        3. [Supplier EER diagram](#man-supplier-eer)
        4. [Supplier SQL](#man-supplier-sql)