<?php
/**
 * Created by PhpStorm.
 * User: xklxq
 * Date: 2020/9/7
 * Time: 13:38
 * Desc：
 */

namespace apivp1\controllers;


use apivp1\models\Contract;
use common\controllers\ActiveBaseController;
use common\helpers\YunhtHelper;
use common\models\Company;
use common\models\UserSigner;
use Yii;

class ContractController extends ActiveBaseController {
	public $modelClass = Contract::class;
	protected $_verbs = ['GET', 'OPTIONS','POST'];
	public function init() {
		parent::init(); // TODO: Change the autogenerated stub
		$this->enableCsrfValidation=false;
	}

	public function behaviors(): array
	{
		$behaviors = parent::behaviors();
		$behaviors['authenticator']['except'] = ['options','notify'];
		return $behaviors;
	}

	public function actions() {
		$actions = parent::actions(); // TODO: Change the autogenerated stub
		unset($actions['delete'], $actions['create'], $actions['update'],$actions['index'],$actions['view']);

		return $actions;
	}

	//授权检测
	public function checkAccess($action, $model = null, $params = []) {
		if ($action == 'list'||$action=='notify'||$action='scount') {
			return true;
		}

		return parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
	}

	public function actionScount() {
		$uid                      = Yii::$app->user->id;
		$query                    = Contract::find();
		$condition['touid']       = $uid;
		$condition['user_status'] = 0;
		$res['unfinished']        = $query->where($condition)->count();
		$condition['user_status'] = 1;
		$res['finished']          = $query->where($condition)->count();

		return $res;
	}

	public function actionList(){
		$uid                      = Yii::$app->user->id;
		$params=Yii::$app->request->queryParams;
		$query                    = Contract::find();
		$condition['touid']       = $uid;
		$condition['user_status']=$params['user_status'];
		$res=$query->where($condition)->select('contractno,id,user_status,status,contracttitle')->all();
		return $res;
	}

	//异步回调接口信息
	public function actionNotify(){
		$request = Yii::$app->request;
		$params  = $request->bodyParams;
		if (Yii::$app->request->isPost){
			$type=$params['noticeType'];
			$data=$params['map']['data'];

			$contractNo=$data['contractNo'];
			foreach ($data['signerList'] as $key=>$val){
				$slist[$val['userId']]=$val['statusCode'];
			}
			$res=Company::find()->one();
			$companyid=$res->signerid;
			$model=Contract::findOne(['contractno'=>$contractNo]);
			$usersigner=UserSigner::find()->where(['uid'=>$model->touid])->one();
			if ($type==1){
				$update['user_status']=$slist[$usersigner->signerid];
				$update['admin_status']=$slist[$companyid];
			}
			if ($type==2){
				$update['user_status']=1;
				$update['admin_status']=1;
				$update['status']=2;
			}
			$model->load($update,'');
			$model->save();
		}
		return true;
	}
}