<?php
/**
 * Created by PhpStorm.
 * User: xklxq
 * Date: 2020/9/11
 * Time: 8:52
 * Desc：
 */

namespace apivp1\controllers;


use apivp1\models\Sms;
use common\controllers\ActiveBaseController;
use common\helpers\SmsHelper;
use Yii;
use yii\web\ServerErrorHttpException;

class SmsController extends ActiveBaseController{
	public $modelClass = Sms::class;

	public function actions() {
		$actions = parent::actions(); // TODO: Change the autogenerated stub
		unset($actions['view'], $actions['delete'], $actions['update'], $actions['index'], $actions['create']);

		return $actions;
	}

	public function checkAccess($action, $model = null, $params = []) {
		if ($action === 'create') {
			return true;
		}

		return parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
	}

	public function actionCreate() {
		$request          = Yii::$app->request;
		$params['mobile'] = $request->getBodyParam('phone_number');
		$params['code']   = rand(100000, 999999);
		$model            = new Sms();
		$this->sendCode($params);
		$model->setScenario('add');
		$model->load($params, '');
		if ( ! $model->save()) {
			throw new ServerErrorHttpException('Server error');
		}

		return $model;
	}

	private function sendCode($data){
		$content=Yii::t('app','Your SMS verification code is: {code}, If you are not operating by yourself, please ignore this message',['code'=>$data['code']]);
		$send['content']="【".Yii::t('app','Mini Hiker')."】".$content;
		$send['mobile']=$data['mobile'];
		$send_result=SmsHelper::send($send);
		if (!$send_result){
			throw new ServerErrorHttpException(Yii::t('app','Failed to send verification code'));
		}
		return true;
	}
}